# Generated by Django 3.0.4 on 2023-02-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtin', '0007_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
